# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jogutier <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/09/06 20:09:01 by jogutier          #+#    #+#              #
#    Updated: 2018/09/06 20:09:20 by jogutier         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_tail
SRCS=srcs/*.c

all:
	@gcc $(SRCS) -o $(NAME)

clean:
	@/bin/rm -f *.o

fclean: clean
	@/bin/rm -f $(NAME)

re: fclean re
